language: node_js
node_js:
  - 0.10
branches:
  only:
    - master
    - active
    - test
install:
  - npm install # should install itself globally via install-g
  - npm i -g batshit # is a development dependency - without auto-install
before_script:
  - which bon # bon must also have automatically got installed
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
