language: node_js
node_js:
  - 0.10
branches:
  only:
    - active
    - test
install:
  - npm install # should install itself globally via install-g
  - which bon # illustrates that bon fails to auto-install
  - npm install -g bon # until the install-g bug is fixed
before_script:
  - echo "\$NODE_PATH is '${NODE_PATH}'"
  - pwd
  - ls $NODE_PATH
  - which datomic-free
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
